import Head from "next/head";
import styles from "./Home.module.css";
import React from "react";
import { TextField, Button } from "@mui/material";
import CategoryTabs from "../../components/CategoryTabs";
import EmptyState from "../../components/EmptyNotes";
import NewNoteModal from "../../components/NewNoteModal";
import createNote from "../../utils/createNote/createNote";

const Home = () => {
  const [open, setOpen] = React.useState(false);
  const handleOpen = () => {
    setOpen(true);
    createNote();
  };
  const handleClose = () => setOpen(false);
  return (
    <>
      <Head>
        <title>Notes</title>
        <meta name="description" content="Generated by create next app" />;
        <link rel="icon" href="/pencil.svg" />
      </Head>

      <main className={styles.main}>
        <TextField
          id="outlined-basic"
          label="Search"
          variant="filled"
          color="info"
          style={{ marginTop: 30, width: "100%", borderRadius: 2 }}
        />
        <div className={styles.categoryButtonContainer}>
          <CategoryTabs />
          <Button onClick={handleOpen} variant="contained">
            + Add Note{" "}
          </Button>
        </div>

        <EmptyState />

        <ul id="notesList"></ul>
        <NewNoteModal handleClose={handleClose} open={open} />
      </main>
    </>
  );
};

export default Home;
